### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-immutable#10]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@super132 please proceed, it's yours

**Comment by super132** [comment]
@dmarkov since the implementation of this project is all here. Should I estimate it them based on my judgement or is there any reference on it? Thanks.

**Comment by super132** [comment]
@dmarkov PR #13 fixed this issue. Would you please close this ticket? Thanks.

**Comment by super132** [comment]
@dmarkov may I know is it fine to close this ticket? Thanks.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by super132** [comment]
@dmarkov it has been 6 days since PR is merged. Please close it.

@yegor256 For this case, how can I urge ticket owner to close it as it has been a very long time ago.

**Comment by yegor256** [comment]
@super132 sure, you're doing it right. it will be closed soon!

**Comment by super132** [comment]
@dmarkov The PR has been merged for a week and this issue is still not yet closed. Would you please close it ?

**Comment by dmarkov** [comment]
@super132 Thank you, I have added **30 mins** to your account in payment/transaction "`AP-84E08732819135715`", time consumed: 192 hours and 38 mins; +30 added to your rating, at the moment it is: [+391](http://www.netbout.com/b/35282?open=rating)

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing
