### ISSUE TITLE
Array class is not immutable when created with a particular constructor.

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-immutable#16]
Consider this code:

```java
@Test
public void immutable() {
    String[] strings = new String[] {"a", "b", "c"};
    final Array<String> array = new Array<String>(strings);
    strings[1] = "WRONG";
    System.out.println(array);
}
```

It ouputs `a, WRONG, c` instead of `a, b, c`.

This commit broke it:

https://github.com/jcabi/jcabi-immutable/commit/551e743a50b9fc679c27d44a6ddd6b2990deddb5

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Suseika good catch, thanks

**Comment by dmarkov** [comment]
@suseika thanks for the ticket, your account was topped for 15 mins, payment AP-77S177656R7861742

**Comment by dmarkov** [comment]
@nesterov-n please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by nesterov-n** [comment]
@yegor256 @Suseika PR was merged. I believe that this issue is done. Can you close it?

**Comment by dmarkov** [comment]
@nesterov-n Many thanks! **30 mins** were added to your account in Transaction ID `AP-9C090712J10646823` (task took 117 hours and 49 mins); added +30 to your rating, now it is equal to [-28](http://www.netbout.com/b/36483?open=rating)
