### ISSUE TITLE
Mark unused methods as deprecated

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-immutable#17]
How about we mark mutators that throw `UnsupportedOperationException` with `@Deprecated` annotation, as Guava does? That way you can visually identify unsupported methods when completion is used within IDE.

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@Suseika good idea, thanks

**Comment by dmarkov** [comment]
@suseika thanks for the report, I topped your acc for 15 mins, payment ID `AP-4PT13179TT310920D`

**Comment by dmarkov** [comment]
@nesterov-n it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by nesterov-n** [comment]
@dmarkov @Suseika Please, check my PR #31

**Comment by nesterov-n** [comment]
@yegor256 Implementing of this feature conflicts with qulice checks. We cannot marks methods with @Deprecated annotation without @deprecated tag in JavaDoc  (MissingDeprecatedCheck). But we cannot add JavaDoc for overrided methods (NoJavadocForOverrideMethods). So this issue cannot be implemented with all our quality checks

**Comment by yegor256** [comment]
@nesterov-n I would recommend to submit a bug to qulice and explain this problem there

**Comment by nesterov-n** [comment]
@Suseika @yegor256 PR was merged. I believe this issue is done. Can you close it?

**Comment by nesterov-n** [comment]
@dmarkov This issue was closed.

**Comment by dmarkov** [comment]
@nesterov-n thank you, added **30 mins** to your acc, payment num is `AP-1JA21896P50998734`, 186 hours and 56 mins spent in total to complete; +30 to your rating, your total score is [-58](http://www.netbout.com/b/36483?open=rating)
