### ISSUE TITLE
Wrong use of generics in ArrayComparator#Reverse

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-immutable#21]
This test would fail:
```java
    @Test
    public void worksWithNonComparable() {
        final ArrayComparator.Reverse<Array<String>> comparator =
            new ArrayComparator.Reverse<Array<String>>();
        comparator.compare(new Array<String>("a"), new Array<String>("b"));
    }
```
`ArrayComparator#Reverse` should be written like this:
```java
    /**
     * Reverse comparator.
     * @param <T> Type of argument
     */
    @Immutable
    final class Reverse<T extends Comparable> 
        implements ArrayComparator<T>, Serializable {
        /**
         * Serialization marker.
         */
        private static final long serialVersionUID = 0x545f489d3ed2eca3L;
        @Override
        public String toString() {
            return "REVERSE";
        }
        @Override
        public int compare(final T left, final T right) {
            return right.compareTo(left);
        }
    }
```

Then that failing test will not compile.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@Suseika good catch thanks

**Comment by dmarkov** [comment]
@suseika thanks for this report, I added 15 mins to your account, in transaction `AP-7T2353111Y323290A`

**Comment by dmarkov** [comment]
@ivanjunckes the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by ivanjunckes** [comment]
@dmarkov do you know where can I get the checkstyle to verify the code before checking in?

**Comment by dmarkov** [comment]
> @dmarkov do you know where can I get the checkstyle to verify the code before checking in?

@ivanjunckes don't ask me technical questions, instead address them either to the author of the ticket or project architect (@yegor256)

**Comment by ivanjunckes** [comment]
@dmarkov ok
@yegor256 do you know where can I get the checkstyle to verify the code before checking in?

**Comment by yegor256** [comment]
@ivanjunckes it's inside qulice project: https://github.com/teamed/qulice

**Comment by ivanjunckes** [comment]
Please review the pull request #27

**Comment by ivanjunckes** [comment]
@dmarkov please assign somebody to review the code #27

**Comment by dmarkov** [comment]
> @dmarkov please assign somebody to review the code #27 

@ivanjunckes sure, will do

**Comment by dmarkov** [comment]
@ivanjunckes the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 added to your rating, current score is: [-240](http://www.netbout.com/b/36097?open=rating)

**Comment by dmarkov** [comment]
@piddubnyi it's yours, please go ahead

**Comment by piddubnyi** [comment]
@Suseika Fix merged now, please close the issue.

**Comment by dmarkov** [comment]
@piddubnyi thanks, I just added **30 mins** to your account, payment `75674592`, 143 hours and 38 mins spent. +30 added to your rating, current score is: [+90](http://www.netbout.com/b/35966?open=rating)
