### ISSUE TITLE
Naming inconsistency in Array

### ISSUE THREAD

**Issue by Suseika** [jcabi/jcabi-immutable#22]
A good practice in programming is that methods named with antonyms should do opposite tasks.

Consider methods `Array#with(T)`, `Array#without(int)` and `Array#less(T)`. 

`Array#with` and `Array#less` are reverse functions: 
```java
arr.with("a").less("a").equals(arr)
```
And `Array#without(int)` operates in incides, not elements, but its name (though not signature) implies it is related to `Array#with(T)`.

I think that names of methods `Array#without(int)` and `Array#less(T)` should be swapped. Of course that breaks reverse compatibility. But maybe in version 2.0?

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Suseika yeah, make sense... we have this mess with names for historical reasons. Let's rename them.

**Comment by dmarkov** [comment]
@suseika many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-9E406740SK386523C`

**Comment by dmarkov** [comment]
@piddubnyi could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by piddubnyi** [comment]
@Suseika fix is merged, please close the issue.

**Comment by Suseika** [comment]
@piddubnyi It isn't merged yet. Please report fixing an issue after it is actually merged.

**Comment by Suseika** [comment]
@piddubnyi I see it is merged now. Closing the issue, thanks.

**Comment by dmarkov** [comment]
@piddubnyi Much appreciated! **30 mins** was added to your account, payment ID `73944322`, time spent is 192 hours and 53 mins; added +30 to your rating, now it is equal to [-60](http://www.netbout.com/b/35966?open=rating)
