### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-immutable#6]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@nathansgreen it's your task, go ahead

**Comment by dmarkov** [comment]
@maurezen many thanks for the report, I topped your account for 15 mins, transaction 49997546

**Comment by nathansgreen** [comment]
@dmarkov @maurezen I created PR #7 for this issue but haven't seen any review activity. Anything I should do?

**Comment by nathansgreen** [comment]
@dmarkov I don't see my login tagged on this issue. Should it be?

**Comment by nathansgreen** [comment]
@maurezen the PR has been merged. Can this issue be closed?

**Comment by maurezen** [comment]
@nathansgreen right, closing this now.

**Comment by dmarkov** [comment]
@nathansgreen thanks, I just added **30 mins** to your account, payment `AP-56B61575DG437373S`

+30 to your rating, your total score is [+100](http://www.netbout.com/b/35107?open=rating)
